spring:
  application.name: whatever
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  sleuth:
    messaging:
      kafka:
        enabled: true
